
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 13 00:54:21 IST 2010
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class libsym {
  /* terminals */
  public static final int DIVIDE = 9;
  public static final int LCBR = 6;
  public static final int LTE = 20;
  public static final int UMINUS = 14;
  public static final int INTEGER = 27;
  public static final int CONTINUE = 39;
  public static final int SEMI = 26;
  public static final int INT = 33;
  public static final int MINUS = 13;
  public static final int STATIC = 35;
  public static final int LT = 19;
  public static final int LP = 2;
  public static final int COMMA = 25;
  public static final int CLASS = 42;
  public static final int RP = 3;
  public static final int PLUS = 12;
  public static final int MULTIPLY = 11;
  public static final int IF = 36;
  public static final int ASSIGN = 8;
  public static final int QUOTE = 30;
  public static final int THIS = 44;
  public static final int DOT = 24;
  public static final int ID = 28;
  public static final int EOF = 0;
  public static final int BOOLEAN = 32;
  public static final int RETURN = 41;
  public static final int RCBR = 7;
  public static final int LB = 4;
  public static final int LAND = 21;
  public static final int EQUAL = 15;
  public static final int TRUE = 47;
  public static final int NEW = 45;
  public static final int error = 1;
  public static final int RB = 5;
  public static final int LOR = 23;
  public static final int NULL = 48;
  public static final int MOD = 10;
  public static final int BREAK = 40;
  public static final int VOID = 31;
  public static final int GTE = 18;
  public static final int ELSE = 37;
  public static final int WHILE = 38;
  public static final int NEQUAL = 16;
  public static final int CLASS_ID = 29;
  public static final int EXTENDS = 43;
  public static final int STRING = 34;
  public static final int LNEG = 22;
  public static final int FALSE = 46;
  public static final int GT = 17;
  public static final int LENGTH = 49;
}

